# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'
  
dpr_pphelp:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /content/drive/MyDrive/DPR/data/pp_help/version1/drp_pphelp_docs.tsv
  id_prefix: 'pphelp:'
