# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'
  
dpr_pphelp:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /content/DPR/data/dpr_pphelp_ascii.tsv
  id_prefix: 'pphelp:'
