# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

pphelp_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /content/drive/MyDrive/DPR/data/dpr_pphelp_test.tsv

pphelp_test_600:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /content/drive/MyDrive/DPR/data/pp_help/version1/train60_dev10_test30/dpr_pphelp_test_0.tsv

pphelp_test_601:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /content/drive/MyDrive/DPR/data/pp_help/version1/train60_dev10_test30/dpr_pphelp_test_1.tsv

pphelp_test_602:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /content/drive/MyDrive/DPR/data/pp_help/version1/train60_dev10_test30/dpr_pphelp_test_2.tsv
